[providers]
python = "3.10"

[build]
buildCommand = "pip install --upgrade pip && pip install -r requirements.txt"

[start]
cmd = "cd Backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONUNBUFFERED = "1"