[build]
builder = "NIXPACKS"
buildCommand = "cd Backend && pip install --no-cache-dir -r requirements-prod.txt"

[deploy]
startCommand = "cd Backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
RAILWAY_ENVIRONMENT = "production"